### PR TITLE
Added output for Firmware

### PR DESCRIPTION
**Pull request by duttabhishek0**
- Firmware.txt contains the link to the list of Firmwares Paper

### CODE REVIEW

**Comment by duttabhishek0** [comment]
Output after running `firmwares.sh` :
image


1. The above script  will store the code including the keyword `fwname`. There is an API [`request_firmware`](https://www.kernel.org/doc/html/v4.13/driver-api/firmware/request_firmware.html#request-firmware-api) , that takes in an argument named `fwname` which corresponds to the firmware name. 

2. So from here, we can get the list of the firmware that are supported in a specific version of kernel

**Review by tapaswenipathak — APPROVED** [review]
cc @PankajGoswami11.

**Comment by duttabhishek0** [comment]
This PR contains:
- Script to get details about the firmwares for different versions:
  - v2.6.39.4
  - v3.0
  - v4.0
  - v5.0
  - v6.0
- A txt file containing the link to the list of Firmware Paper
- log files related to firmwares(both logs and shortlogs)
(for the following Versions:
  - v2.6.39.4
  - v3.0
  - v4.0
  - v5.0
  - v6.0)
- Scripts to get such log files

**Review by Madhupatel08 — APPROVED** [review]
git log --all --grep="string"

**Comment by duttabhishek0** [comment]
- Added link to the drive that contains the data dump files.

**Review by tapaswenipathak — APPROVED** [review]

**Comment by duttabhishek0** [comment]
#8 firmware

**Pull request merged**
