### PR TITLE
Added a new no_of_files.sh file

### PR DESCRIPTION
**Pull request by KavitaMeena23**
No. of files present in each version of linux kernel

```Output is diff on every run```

### CODE REVIEW

**Comment by KavitaMeena23** [comment]
Output on 1st run:
```
fatal: Cannot switch branch to a non-commit 'v2.6.11'
fatal: Cannot switch branch to a non-commit 'v2.6.11-tree'
v2.6.12  17842
v2.6.12-rc2  17773
v2.6.12-rc3  17799
v2.6.12-rc4  17831
v2.6.12-rc5  17843
v2.6.12-rc6  17842
v2.6.12.1  17842
v2.6.12.2  17842
v2.6.12.3  17842
v2.6.12.4  17842
v2.6.12.5  17842
v2.6.12.6  17842
v2.6.13  18092
```

Output on 2nd run:
```
fatal: Cannot switch branch to a non-commit 'v2.6.11'
fatal: Cannot switch branch to a non-commit 'v2.6.11-tree'
v2.6.12  17399
v2.6.12-rc2  17330
v2.6.12-rc3  17356
v2.6.12-rc4  17388
v2.6.12-rc5  17400
v2.6.12-rc6  17399
v2.6.12.1  17399
v2.6.12.2  17399
v2.6.12.3  17399
v2.6.12.4  17399
v2.6.12.5  17399
v2.6.12.6  17399
v2.6.13  18129
```

Output on 3rd run:
```
fatal: Cannot switch branch to a non-commit 'v2.6.11'
fatal: Cannot switch branch to a non-commit 'v2.6.11-tree'
v2.6.12  17371
v2.6.12-rc2  17302
v2.6.12-rc3  17328
v2.6.12-rc4  17360
v2.6.12-rc5  17372
v2.6.12-rc6  17371
v2.6.12.1  17371
v2.6.12.2  17371
v2.6.12.3  17371
v2.6.12.4  17371
v2.6.12.5  17371
v2.6.12.6  17371
v2.6.13  18092
```

**Review by ahsmha — COMMENTED** [review]
script seems to be working fine for me. @KavitaMeena23 can you try running it again?

**Comment by ahsmha** [comment]
Output on first run : 
```
v2.6.12     17346
v2.6.12-rc2     17277
v2.6.12-rc3     17303
v2.6.12-rc4     17335
v2.6.12-rc5     17347
v2.6.12-rc6     17346
v2.6.12.1     17346
v2.6.12.2     17346
v2.6.12.3     17346
v2.6.12.4     17346
v2.6.12.5     17346
v2.6.12.6     17346
v2.6.13     18076
v2.6.13-rc1     17727
v2.6.13-rc2     17726
v2.6.13-rc3     17812
v2.6.13-rc4     18061
v2.6.13-rc5     18071
v2.6.13-rc6     18072
v2.6.13-rc7     18076
v2.6.13.1     18076
v2.6.13.2     18076
v2.6.13.3     18076
v2.6.13.4     18076
v2.6.13.5     18076
v2.6.14     18416
v2.6.14-rc1     18381
v2.6.14-rc2     18399
v2.6.14-rc3     18396
v2.6.14-rc4     18404
v2.6.14-rc5     18415
v2.6.14.1     18416
v2.6.14.2     18417
v2.6.14.3     18417
v2.6.14.4     18417
v2.6.14.5     18417
v2.6.14.6     18417
v2.6.14.7     18417
v2.6.15     18793
v2.6.15-rc1     18797
v2.6.15-rc2     18793
v2.6.15-rc3     18793
v2.6.15-rc4     18793
v2.6.15-rc5     18793
```

Output on second run : 
```
v2.6.12     17346
v2.6.12-rc2     17277
v2.6.12-rc3     17303
v2.6.12-rc4     17335
v2.6.12-rc5     17347
v2.6.12-rc6     17346
v2.6.12.1     17346
v2.6.12.2     17346
v2.6.12.3     17346
v2.6.12.4     17346
v2.6.12.5     17346
v2.6.12.6     17346
v2.6.13     18076
v2.6.13-rc1     17727
v2.6.13-rc2     17726
v2.6.13-rc3     17812
v2.6.13-rc4     18061
v2.6.13-rc5     18071
v2.6.13-rc6     18072
v2.6.13-rc7     18076
v2.6.13.1     18076
v2.6.13.2     18076
v2.6.13.3     18076
v2.6.13.4     18076
v2.6.13.5     18076
v2.6.14     18416
v2.6.14-rc1     18381
v2.6.14-rc2     18399
v2.6.14-rc3     18396
v2.6.14-rc4     18404
v2.6.14-rc5     18415
v2.6.14.1     18416
v2.6.14.2     18417
v2.6.14.3     18417
v2.6.14.4     18417
v2.6.14.5     18417
v2.6.14.6     18417
v2.6.14.7     18417
v2.6.15     18793
v2.6.15-rc1     18797
v2.6.15-rc2     18793
v2.6.15-rc3     18793
v2.6.15-rc4     18793
v2.6.15-rc5     18793
```

**Comment by ahsmha** [comment]
[output1](https://imgur.com/a/yo1fzp5)

[output2](https://imgur.com/a/g6jvQcC)

**Review by tapaswenipathak — APPROVED** [review]

**Pull request merged**
